import type { Metadata } from "next";
import "./globals.css";
import { ConditionalNavbar } from "./components/ConditionalNavbar";
import DashboardLayout from "./components/DashboardLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0, background: 'transparent' }}>
        <ConditionalNavbar />
        <DashboardLayout>{children}</DashboardLayout>
      </body>
    </html>
  );
}
