"use client";
import React from "react";

export default function TermsOfServicePage() {
  return (
    <div className="tos-bg">
      <div className="tos-content">
        <h1 className="tos-title">Terms Of Service</h1>
        <div className="tos-card">
          <p className="tos-text">
            By accessing or using Warmly, you agree to use the platform in a lawful, respectful, and responsible manner, and to ensure that all information you provide—such as contacts, introductions, and notes—is accurate and obtained with proper consent. You are fully responsible for maintaining the security of your account and any actions taken under it. Warmly provides tools to help streamline introductions, follow-ups, and investor management, but we do not guarantee communication outcomes, delivery of reminders, or the accuracy of insights generated by the system. We may update, modify, or discontinue features at any time as we improve the service. Warmly is not liable for data loss, missed opportunities, or damages resulting from how the platform is used. Continued use of the service indicates your acceptance of any updates to these terms, and if you do not agree, you should stop using Warmly immediately.
          </p>
        </div>
      </div>
      <style jsx>{`
        .tos-bg {
          min-height: 100vh;
          background: url("/backeground.jpg");
          background-size: cover;
          background-position: center;
          display: flex;
          align-items: flex-start;
          width: 100%;
        }
        .tos-content {
          padding: 32px 38px 35px 38px;
          width: 100%;
        }
        .tos-title {
          font-size: 2.2rem;
          font-weight: 700;
          color: #fff;
          margin-bottom: 24px;
        }
        .tos-card {
          background: #fff;
          border-radius: 14px;
          box-shadow: 0 3px 22px #595fcc18;
          padding: 38px 45px;
          max-width: 100%;
        }
        .tos-text {
          font-size: 1.22rem;
          line-height: 1.5;
          color: #222;
          margin: 0;
          text-align: center;
        }
        @media (max-width: 700px) {
          .tos-content {
            padding: 20px 2vw 8px 2vw;
          }
          .tos-card {
            padding: 24px 7px;
          }
          .tos-text {
            font-size: 1.02rem;
          }
        }
      `}</style>
    </div>
  );
}
