"use client";
import React from 'react';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen w-full bg-linear-to-br from-gray-950 via-slate-800 to-blue-950 flex justify-center items-center p-5 md:p-10">
      <div className="max-w-[900px] w-full">
        <div className="bg-[#0A0C14] border border-white/10 rounded-2xl p-6 md:p-12 shadow-[0_20px_50px_rgba(0,0,0,0.5)]">
          
          <div className="flex items-center gap-4 mb-10 border-b border-white/5 pb-6">
            <div>
              <h1 className="text-2xl md:text-[1.75rem] font-bold text-white tracking-tight m-0 leading-tight">
                Terms of Service
              </h1>
              <p className="text-[0.85rem] color-[#64748b] mt-1 text-slate-500">
                Last Updated: January 2026
              </p>
            </div>
          </div>

          <div className="flex flex-col gap-8">
            <section>
              <h2 className="text-white text-[1.1rem] font-bold mb-3">1. Acceptance of Terms</h2>
              <p className="text-[0.95rem] leading-relaxed text-slate-400 m-0 text-left">
                By accessing or using Warmly, you agree to use the platform in a lawful, respectful, and responsible manner, and to ensure that all information you provide—such as contacts, introductions, and notes—is accurate and obtained with proper consent.
              </p>
            </section>

            <section>
              <h2 className="text-white text-[1.1rem] font-bold mb-3">2. User Responsibilities</h2>
              <p className="text-[0.95rem] leading-relaxed text-slate-400 m-0 text-left">
                You are fully responsible for maintaining the security of your account and any actions taken under it. Warmly provides tools to help streamline introductions, follow-ups, and investor management.
              </p>
            </section>

            <section>
              <h2 className="text-white text-[1.1rem] font-bold mb-3">3. Service Limitations</h2>
              <p className="text-[0.95rem] leading-relaxed text-slate-400 m-0 text-left">
                We do not guarantee communication outcomes, delivery of reminders, or the accuracy of insights generated by the system. We may update, modify, or discontinue features at any time as we improve the service.
              </p>
            </section>

            <section>
              <h2 className="text-white text-[1.1rem] font-bold mb-3">4. Liability & Termination</h2>
              <p className="text-[0.95rem] leading-relaxed text-slate-400 m-0 text-left">
                Warmly is not liable for data loss, missed opportunities, or damages resulting from how the platform is used. Continued use of the service indicates your acceptance of any updates to these terms, and if you do not agree, you should stop using Warmly immediately.
              </p>
            </section>
            
            <section>
              <h2 className="text-white text-[1.1rem] font-bold mb-3">5. Contact</h2>
              <p className="text-[0.95rem] leading-relaxed text-slate-400 m-0 text-left">
                If you have questions, reach us at <span className="text-blue-500 cursor-pointer hover:underline">support@warmintro.app</span>
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}