"use client";
import React from "react";

export default function TermsOfServicePage() {
  return (
    <div className="tos-bg">
      <div className="tos-content">
        {/* Main Card Container matches image_2c245c.jpg */}
        <div className="tos-card">
          
          {/* Header with Icon Section */}
          <div className="tos-header">
            <div className="tos-icon-wrapper">
              <svg 
                width="24" height="24" viewBox="0 0 24 24" fill="none" 
                stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"
              >
                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
              </svg>
            </div>
            <div>
              <h1 className="tos-title">Terms of Service</h1>
              <p className="tos-update-date">Last Updated: January 2026</p>
            </div>
          </div>

          {/* Sectioned Content for better Professional Look */}
          <div className="tos-sections">
            <section>
              <h2 className="tos-section-title">1. Acceptance of Terms</h2>
              <p className="tos-text">
                By accessing or using Warmly, you agree to use the platform in a lawful, respectful, and responsible manner, and to ensure that all information you provide—such as contacts, introductions, and notes—is accurate and obtained with proper consent.
              </p>
            </section>

            <section>
              <h2 className="tos-section-title">2. User Responsibilities</h2>
              <p className="tos-text">
                You are fully responsible for maintaining the security of your account and any actions taken under it. Warmly provides tools to help streamline introductions, follow-ups, and investor management.
              </p>
            </section>

            <section>
              <h2 className="tos-section-title">3. Service Limitations</h2>
              <p className="tos-text">
                We do not guarantee communication outcomes, delivery of reminders, or the accuracy of insights generated by the system. We may update, modify, or discontinue features at any time as we improve the service.
              </p>
            </section>

            <section>
              <h2 className="tos-section-title">4. Liability & Termination</h2>
              <p className="tos-text">
                Warmly is not liable for data loss, missed opportunities, or damages resulting from how the platform is used. Continued use of the service indicates your acceptance of any updates to these terms, and if you do not agree, you should stop using Warmly immediately.
              </p>
            </section>
            
            <section>
              <h2 className="tos-section-title">5. Contact</h2>
              <p className="tos-text">
                If you have questions, reach us at <span className="tos-link">support@warmintro.app</span>
              </p>
            </section>
          </div>
        </div>
      </div>

      <style jsx>{`
        .tos-bg {
          min-height: 100vh;
          background: #010204; /* Dark Midnight Base */
          display: flex;
          justify-content: center;
          align-items: center;
          width: 100%;
          padding: 40px 20px;
        }
        .tos-content {
          max-width: 900px;
          width: 100%;
        }
        .tos-card {
          background: #0A0C14; /* Deep Card Background */
          border: 1px solid rgba(255, 255, 255, 0.1);
          border-radius: 16px;
          padding: 48px;
          box-shadow: 0 20px 50px rgba(0, 0, 0, 0.5);
        }
        .tos-header {
          display: flex;
          align-items: center;
          gap: 16px;
          margin-bottom: 40px;
          border-bottom: 1px solid rgba(255, 255, 255, 0.05);
          padding-bottom: 24px;
        }
        .tos-icon-wrapper {
          opacity: 0.9;
        }
        .tos-title {
          font-size: 1.75rem;
          font-weight: 700;
          color: #fff;
          margin: 0;
          letter-spacing: -0.02em;
        }
        .tos-update-date {
          font-size: 0.85rem;
          color: #64748b;
          margin-top: 4px;
        }
        .tos-sections {
          display: flex;
          flex-direction: column;
          gap: 32px;
        }
        .tos-section-title {
          color: #fff;
          font-size: 1.1rem;
          font-weight: 700;
          margin-bottom: 12px;
        }
        .tos-text {
          font-size: 0.95rem;
          line-height: 1.7;
          color: #94a3b8; /* Muted slate for better readability */
          margin: 0;
          text-align: left;
        }
        .tos-link {
          color: #3b82f6;
          cursor: pointer;
        }
        @media (max-width: 700px) {
          .tos-card {
            padding: 24px;
          }
          .tos-title {
            font-size: 1.4rem;
          }
        }
      `}</style>
    </div>
  );
}