# Use Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your app code and data folder into the container
COPY app ./app

# Run the FastAPI app
CMD ["uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "8000"]